### ISSUE TITLE
Meeting 2/15/24

### ISSUE THREAD

**Issue by Powerlated** [Powerlated/FEH_Robot_Team_C2#12]
**Team Meeting 2/15/2024** 

Begin: 6:00pm 
Place: Pomerene 260 
Planned End: 9:00pm 
End: 7:50pm 

**Agenda** 

- [ ] Talk about reworking bot to use 4-bar 
- [ ] Discuss APP R05-1: Initial Project Schedule 
- [ ] Discuss APP R05-3: Agendas and Notes 

**In Attendance** 
Brian, Griffin, Drew 

Sam is sick 

**Notes** 

- Formulated a plan for completed upcoming APPs. 
- created a plan for completing the project schedule over the weekend on GitHub 
- created a time sheet format and testing log 
- submitted the first parts order 
- discussed 4-bar for kiosk high and low buttons, and the fuel levers. Luggage will be handled by a little holder on top of the 4-bar mechanism that acts like a dumptruck. We will be able to raise the 4-bar and the luggage will just slide out. 
- Brian will draw up a CAD model to better visualize functionality. The team will go ahead with the rack-and-pinion design for now 

**To-Do** 

**Project Schedule** 

- [ ] Griffin: half of APP assignments 
- [ ] Sam: team meetings 
- [ ] Brian: all project milestones 
- [ ] Drew: APP R05-2, documentation 
- [ ] Everyone: add time from this week into the appropriate time sheet
